x-common-env: &common-env
  NATS_SERVERS: nats://nats:4222
  REDIS_HOST: 'redis'
  REDIS_PORT: ${REDIS_PORT}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: 'db'
  DB_PORT: ${DB_PORT}

services:
  nats:
    image: nats:alpine
    ports:
      - '4222:4222'

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  users:
    build:
      context: .
    command:
      - pnpm
      - run
      - start:debug
      - users
    ports:
      - '3000:3000'
      - 9229:9229
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - nats
      - redis
      - db
    environment:
      <<: [ *common-env ]

  books:
    build:
      context: .
    command:
      - pnpm
      - run
      - start:debug
      - books
    ports:
      - '3001:3000'
      - '9230:9229'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - nats
      - redis
      - db
    environment:
      <<: [ *common-env ]

volumes:
  node_modules:

