{
 "title": "Library app Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP status",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (increase(http_server_duration_milliseconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "stat",
   "description": "Represents the ratio of regular v.s. 500 responses",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "1-$errors/$normal", "type": "math" }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P95 response time"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request / endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "round(sort_desc(sum by(http_route, http_method, exported_job) (increase(http_server_duration_milliseconds_count[$__range]))), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expensive endpoints",
   "type": "table",
   "description": "Total time spent responding to an endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "round(sort_desc(sum by(http_route, http_method, exported_job) (increase(http_server_duration_milliseconds_sum[$__range]))), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "filters": [
      {
       "id": "0bb8e0ad",
       "operator": "=",
       "scope": "span",
       "tag": "kind",
       "value": [ "server" ],
       "valueType": "keyword"
      },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Log trail",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{service_name=~\"users|books\"}"
    }
   ]
  },
  {
   "title": "NATS client req/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(nats_client_request_requests_total[$__rate_interval])",
     "legendFormat": "{{messaging_destination}}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Bull jobs run",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "round(scan_overdue_users_count, 1)",
     "legendFormat": "{{messaging_destination}}"
    },
    {
     "expr": "round(scan_overdue_books_count, 1)",
     "legendFormat": "{{messaging_destination}}"
    }
   ]
  },
  {
   "title": "Bull job duration (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(scan_overdue_users_bucket[$__rate_interval])))",
     "legendFormat": "scan-overdue-users"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(scan_overdue_books_bucket[$__rate_interval])))",
     "legendFormat": "scan-overdue-books"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "EventLoop utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_utilization_percent",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(nodejs_cpu_usage_microseconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum by(service_name) (nodejs_memory_kilobytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "targets": [
    { "expr": "redis_db_keys", "legendFormat": "Total keys" },
    {
     "expr": "increase(redis_keys_evicted_total[$__rate_interval])",
     "legendFormat": "Keys evicted"
    },
    {
     "expr": "increase(redis_keys_expired_total[$__rate_interval])",
     "legendFormat": "Keys expired"
    }
   ]
  },
  {
   "title": "Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "targets": [
    { "expr": "redis_commands_per_second", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "targets": [
    { "expr": "redis_clients_connected", "legendFormat": "Clients" },
    { "expr": "redis_clients_blocked", "legendFormat": "Blocked clients" }
   ]
  }
 ]
}