receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: '0.0.0.0:8889'

  logging:

  jaeger:
    endpoint: 'jaeger:14250'
    tls:
      insecure: true

processors:
  batch:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [50ms, 100ms, 200ms, 500ms, 1000ms, 2500ms, 5000ms]
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.route
      - name: nest.controller_method
    dimensions_cache_size: 1000
    metrics_flush_interval: 15s

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  # extensions: [pprof, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [logging, prometheus]
